### ISSUE TITLE
[BUG] Bulk-Edit Dialog Text not fully translated

### ISSUE THREAD

**Issue by sukisoft** [paperless-ngx/paperless-ngx#1018]
### Description

When using the bulk edit feature coming from the listview, there is some small translation bug.

![2022-05-24_06-35](https://user-images.githubusercontent.com/88422038/169950286-4a98baf3-5e68-4f0e-88e4-0e4d3b78ecb9.png)

I am sorry for spooling such small tickets... I will try to test the next release and set it up on a different machine to prevent creating all those small bugs which may distract the contributors from creating new features.

### Steps to reproduce

1. go to documents view
2. choose one single document and use the checkbox to select it for bulk-edit
3. choose tags and select 2 or more tags
4. hit apply
5. dialog appears with missing translation text

### Paperless-ngx version

1.7.1

### Host OS

Synology DSM 6.2.x

### Installation method

Docker

### Browser

Chrome 101.0.4951.64

**Comment by shamoon** [comment]
No worries, always happy to fix small things like this. For this one it turns out the string is just partially translated in crowdin, there are some others too: 

- https://crowdin.com/translate/paperless-ngx/16/en-de#1338
- https://crowdin.com/translate/paperless-ngx/16/en-de#1340
- https://crowdin.com/translate/paperless-ngx/16/en-de#1342

Feel free to translate there or you can just paste it here and I'll put it in if you dont feel like setting up a crowdin account.

**Comment by shamoon** [comment]
Great thanks! Yea its pretty friendly but powerful
