### ISSUE TITLE
[BUG] extended search by "created" produce wrong results

### ISSUE THREAD

**Issue by Conspir3D** [paperless-ngx/paperless-ngx#1100]
### Description

When searching with extended search by "created" date i get false results. See Screenshot below where i search for: created:[20220101 TO 20220331]

The result also display me some results from 20220401.

This also happens by other timespans, mostly +1 day is within the resultset
![search_error](https://user-images.githubusercontent.com/13586686/172152647-5bc1d941-f8b8-40df-80b6-238ef94f86fd.png)
.

### Steps to reproduce

1. Enter Search: created:[20220101 TO 20220331]
2. view results if you have documents created on 20220401

### Paperless-ngx version

1.7.1

### Host OS

Debian with kubernetes, paperlass as container

### Installation method

Docker

### Browser

Chrome

**Comment by Conspir3D** [comment]
This btw is a behavior  i already noticed in paperless-ng (last version), so this is maybe an old bug.

**Comment by Conspir3D** [comment]
Maybe related to #947

**Comment by shamoon** [comment]
Yes Id guess this is timezone related and I think the above PR will fix. Btw, for that query you can just use use the "created" dropdowns which are there (see screenshot) i.e. documents?created__date__lt=2022-04-01&created__date__gt=2021-12-31 but note that in the current version you still get wonky behavior with that because that date gets converted to a localized date, again the above PR fixes that.

If youre OK with it I think we should close this in favor of that PR and can see how things go after the next release.

**Comment by Conspir3D** [comment]
Thank you for answering.
I could use the dropdowns but i use querys a lot with external scripts to genreate automated exports.
But we can close this for now and see how it works after the PR is approved.
