### ISSUE TITLE
[BUG] Thumbnail not created properly

### ISSUE THREAD

**Issue by fantasticle** [paperless-ngx/paperless-ngx#1372]
### Description

I uploaded a document after updating paperless-ngx to the newest release and the corresponding thumbnail is not generated properly. Unfortunately, I could not reproduce it with other documents. The document is created via `Gnostice eDocEngine V4.0.0.633`.

Original:
<img width="1021" alt="original_doc" src="https://user-images.githubusercontent.com/84633558/183302174-fb197fe4-811e-4f02-9dfa-f51ec38981de.png">

Thumbnail (.webp => changed ending to .png to support uploading to Github):
![2022-08-05 Beleg_20220805143350664 pdf-thumbnail](https://user-images.githubusercontent.com/84633558/183302198-e2fa19c0-ca26-4da7-bc95-741b517c29af.png)

That's the log file - btw - I cannot scroll it anymore (macOS and Chrome):
```
[2022-08-07 18:47:39,641] [DEBUG] [paperless.consumer] Generating thumbnail for Beleg_20220805143350664.pdf...
[2022-08-07 18:47:39,644] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-vb56hrm3/archive.pdf[0] /tmp/paperless/paperless-vb56hrm3/convert.webp
```

### Steps to reproduce

Not really reproducible because of lack of reproducibility by myself :-(

### Webserver logs

```bash
-
```

### Paperless-ngx version

1.8.0

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

some not relevant to thumbnail generation

**Comment by stumpylog** [comment]
If you consume the document again (you'd need to delete it first), does a thumbnail get produced?  Or is there anything special about this document?

**Comment by fantasticle** [comment]
Nothing special about the document. After deletion and reupload the thumbnail still looks the same.

**Comment by stumpylog** [comment]
Huh, that is a bizarre output.  What does the archive (not original) downloaded PDF look like?  Is it also weird or is this just the thumnail?

**Comment by Ofloo** [comment]
For me the pages don't render in view completely but for those files the tumbnails don't either, use internal browser viewer enabled, try disabling it and see if the same problem happens too the pdf if it does then it's exactly the same issue that I've got. Because in chromium it does render the pdf view for me but in firefox it doesn't however in both cases the tumbnails don't render properly.

**Comment by Ofloo** [comment]
I think they might be related since the thumbnails are missing the exact same content for me in view mode.

**Comment by Ofloo** [comment]
I think it's related to the bug pdf.js viewer thing. The thumbnails are rendered through that lib, if you enable browser mode then you view the pdf from your browser while the thumbnail is generated from the internal viewer. And that's why some pdf's are missing some data. At least that's my 2c

**Comment by shamoon** [comment]
The thumbnails are actually images (recently changed to .webp format) that are generated by the backend. The PDF preview and the pop-ups when you hover the preview icon are both generated. See screenshots.

I agree it seems very coincidental that the thumbnail looks the same but since the thumbnails dont use pdf.js Im not sure that any fix(s) would actually be the same

<img width="834" alt="Screen Shot 2022-09-05 at 10 35 27 AM" src="https://user-images.githubusercontent.com/4887959/188496010-e238405e-b287-4fd5-8fe8-2f164de9d828.png">
<img width="826" alt="Screen Shot 2022-09-05 at 10 39 02 AM" src="https://user-images.githubusercontent.com/4887959/188496382-fc29bd2c-7a99-41d9-a0a7-f7d94be222ee.png">

**Comment by Ofloo** [comment]
somehow it is related, I'm having a hard time believing it is a coincidence look even on chromium disabling use browser, ..
![afbeelding](https://user-images.githubusercontent.com/2203497/188496810-d0d1a6ba-4858-4de0-9ad6-7f19c66a937f.png)
![afbeelding](https://user-images.githubusercontent.com/2203497/188496850-3841143f-208a-493c-aae8-3be9f456c449.png)
after enableing browser build in viewer

![afbeelding](https://user-images.githubusercontent.com/2203497/188496966-da7ec350-9b82-4968-9ffc-e29b862f4abf.png)

**Comment by fantasticle** [comment]
> Huh, that is a bizarre output. What does the archive (not original) downloaded PDF look like? Is it also weird or is this just the thumnail?

Looks like the original document. It is only the thumbnail that goes rogue.

**Comment by Ofloo** [comment]
For me it's actually both in firefox and thumbnail in chromium-browser
