### ISSUE TITLE
[BUG] Files (pdf) in the consume folder are not processed automatically

### ISSUE THREAD

**Issue by queen4me** [paperless-ngx/paperless-ngx#1443]
### Description

Whatever files I put into the consume folder, they won't be processed.
Uploading documents no problem. I'm deeply impressed of the power paperless-ngx provides.

### Steps to reproduce

After saving some pdf files into the comsume folder nothing happens. No processing.

### Paperless-ngx version

1.8.0

### Host OS

Ubuntu 20.04

### Installation method

Docker - linuxserver.io image

**Comment by shamoon** [comment]
Firstly, you’re using lsio image so potentially an issue there or with your setup (and since this functionality of course does work I have to assume that).

also, you will want to provide them with more info eg your compose file, logs etc. Good luck, of course if you discover an actual bug in paperless please raise it here.

**Comment by queen4me** [comment]
I'll give "your" docker image a try.
