### ISSUE TITLE
[BUG] PDFs containing XFA forms are truncated during processing

### ISSUE THREAD

**Issue by jce-zz** [paperless-ngx/paperless-ngx#1542]
### Description

I have tried to have Paperless-NGX consume a bunch of multi-page PDFs generated out of a SAP system containing XFA form parts by use of a shared consume folder on the local file system.

The processing runs through without any visible error in the UI, but on checking the resulting OCR'd PDFs, the I found the content was very different from the original. In fact, the resulting PDF does not only miss inidividual pages but the whole XFA content is somehow "cut out" and the remaining parts are fused together into a newly composed single-page doc.

I also checked the Paperless log file and did not find any errors logged during consumption. Howev, I found several errors from the Tesseract parser which seem to be generated when I view/edit a consumed file.

Are there any known issues with PDFs containing XFA content? How can I circumvent the issue?

### Steps to reproduce

1. Drop a multi-page PDF containing XFA form content into the consume folder
2. Let Paperless-ngx consume the file
3. Check the resulting OCR'd file and observe all XFA content gone

### Webserver logs

```bash
Log excerpt for document consumption:
[2022-09-06 14:02:40,977] [INFO] [paperless.consumer] Consuming 2016MY-webforms.pdf
[2022-09-06 14:02:40,979] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2022-09-06 14:02:40,981] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2022-09-06 14:02:40,987] [DEBUG] [paperless.consumer] Parsing 2016MY-webforms.pdf...
[2022-09-06 14:02:41,121] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /usr/src/paperless/consume/2016MY-webforms.pdf
[2022-09-06 14:02:41,240] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/usr/src/paperless/consume/2016MY-webforms.pdf', 'output_file': '/tmp/paperless/paperless-qa_m7gbv/archive.pdf', 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-qa_m7gbv/sidecar.txt'}
[2022-09-06 14:02:41,949] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.
[2022-09-06 14:02:41,990] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-qa_m7gbv/archive.pdf
[2022-09-06 14:02:41,991] [DEBUG] [paperless.consumer] Generating thumbnail for 2016MY-webforms.pdf...
[2022-09-06 14:02:41,998] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-qa_m7gbv/archive.pdf[0] /tmp/paperless/paperless-qa_m7gbv/convert.webp
[2022-09-06 14:02:44,376] [DEBUG] [paperless.consumer] Saving record to database
[2022-09-06 14:02:44,377] [DEBUG] [paperless.consumer] Creation date from st_mtime: 2022-09-06 13:40:34.154943+02:00
[2022-09-06 14:02:44,395] [INFO] [paperless.handlers] Assigning document type Mitteilung to 2022-09-06 2016MY-webforms
[2022-09-06 14:02:44,481] [DEBUG] [paperless.consumer] Deleting file /usr/src/paperless/consume/2016MY-webforms.pdf
[2022-09-06 14:02:44,724] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-qa_m7gbv
[2022-09-06 14:02:44,725] [INFO] [paperless.consumer] Document 2022-09-06 2016MY-webforms consumption finished

Errors from parser during viewing:
[2022-09-06 14:04:14,677] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.adobe.com/xfa/promoted-desc/}embeddedHref: . Error: 'http://ns.adobe.com/xfa/promoted-desc/'
[2022-09-06 14:04:14,677] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.adobe.com/xfa/promoted-desc/}Schema_Annotation: . Error: 'http://ns.adobe.com/xfa/promoted-desc/'
```

### Paperless-ngx version

1.8.0

### Host OS

Synology DSM 7.1-42661 Update 2

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
I think there's probably a few issues going on here.

- XFA forms aren't permitted in PDF/A format ([wikipedia](https://en.wikipedia.org/wiki/XFA)), so it gets flattened, wherein something breaks.  I would expect the content and pages to exist, just not be live/editable
- Per [Adobe](https://helpx.adobe.com/livecycle/kb/xfa-pdf-forms-policy-protected-documents-not-displayed.html), Firefox and Chrome can't display XFA
- OCRMyPDF [makes a brief mention about XFA](https://ocrmypdf.readthedocs.io/en/latest/release_notes.html?highlight=xfa#v7-3-0) in an old release note

If you're able to provide a PDF with these forms,  we might be able to at least reproduce it and check with the libraries which handle the OCR and see if the support is something which can work.  I would warn, probably unlikely since it's proprietary Abode.

All that said, if you're looking to use paperless for just organizing these forms and don't need the archive file, the original file should be untouched and contain the XFA.  You can disable the archive with `PAPERLESS_OCR_MODE=skip_noarchive`

**Comment by jce-zz** [comment]
The documents in question are actually not even editable, but just exports of a web application collecting data in forms. When I open them in a PDF Editor (e.g. PDF-Xchange) it tells me that there are XFA form fields, but nothing really editable. I would have also expected that the content just remains static when saving as PDF/A but also PDF-Xchange does not allow me to saveit as PDF/A and just throws an error.

I don't need any special capabilities besides that these documents are correctly displayed in Paperless-ngx and are also OCR'd, although the latter is not critical.

I cannot switch off archiving in general, as these are only 30 from ~3000 documents and all the rest I need archived and they are working fine.

I need to see how to provide you a file as they contain personal data I might not be able to share.

**Comment by jce-zz** [comment]
OK, I think I found a simple solution for my personal problem. I just need to "print" the files again as PDF (e.g. with PDF-Xchange) and then the resulting PDFs are plain, non-XFA ones. As I don't have that many documents, this is a workable solution for me.

However, it would be good if Paperless-ngx would actually throw an error in case such files are encountered during consumption and not just silently consume a truncated file. This would not be a fix for the root cause, but an improvement in recognizing the problem.

**Comment by stumpylog** [comment]
The OCRMyPDF release notes indicate it should raise an error when trying to do something with XFA, so it may be a regression in the detection there.  With a file (not containing personal/protected data), that could be confirmed.  Maybe the format or string it looks for changed.

**Comment by jce-zz** [comment]
I found this example file from Adobe with dynamic XFA content (which my files apparently also have) and tried to consume it. This time an error is thrown by Paperless-ngx, although very generic and not really helpful.
[Purchase Order.pdf](https://github.com/paperless-ngx/paperless-ngx/files/9499547/Purchase.Order.pdf)

**Comment by stumpylog** [comment]
When I run that file through, I do get an error, with the message indicating it contains Adobe proprietary stuff and can't be processed.  So that seems correct and includes a message which makes sense to me.  Do you get a different message in the logs?

For the files you are producing, there must be some difference which allows them through without error, but then produces mangled files.

**Comment by jce-zz** [comment]
Yes, my files are different. They are using tables that are dynamically sized and dynamic fields for page no. So, in fact, the whole doc is layouted on the fly by the PDF Reader based on the amount of content in each table cell. This seems to be one of the XFA features. And this whole dynamically layouted content is just removed by OCRMyPDF. But strangely, the page number fields still work, e.g. instead "5/5" they show now "1/1". And no error is thrown. 

Unfortunately, I cannot really share my files as they contain personal data and I have no means to remove the data. I also couldn't find similar example files on the Internet so far.

**Comment by stumpylog** [comment]
If possible, I would try to create a document you are able to share, and provide it up to the OCRMyPDF team to analyze why chunks go missing, instead of being detected as containing livecycle data.

**Comment by torwag** [comment]
The problem with XFA-based documents is that none (afaik) of the open source libraries is capable to open them. I am surprised to read that @jce-zz is at least partially able to open them. 
Usually if you try to open them you are greeted with a standard text, which claims that you should use Adobe Acrobat Reader to open those files. Don't think this would work with mobile versions of Adobe... no just Mac and Windows are capable. Linux with some old adobe versions which aren't supported anymore.

Keep in mind that the XFA-technique (which was never a standard) is obsolete since many years and even Adobe does not work on it anymore. Even the Adobe Dreamweaver product to produce those forms is obsolete by now.

I know many companies are still using them and is downright a PITA to deal with them.

The intermediate solution was already mentioned. Print the PDF (in Adobe) as PDF again. This flattens the PDF and creates a compatible version which can be opened by any reader, including the libs of paperless-ngx. Albeit, be aware you lose the form features in that case.  

Unfortunately, there is nothing more paperless-ngx could do about it. If there will ever be some libs which can open XFA-based PDFs and convert them e.g. to PDF/A. I guess that would be something which could be plugged as an extra step into the consume pipeline instead of adding it as an integral part to paperless-ngx.

And once more, yes it is a PITA. Talk to your IT department and ask them why they use tech which is marked obsolete since 2017 as Adobe never managed to put this into an ISO standard.

**Comment by jce-zz** [comment]
> If possible, I would try to create a document you are able to share, and provide it up to the OCRMyPDF team to analyze why chunks go missing, instead of being detected as containing livecycle data.

Sorry, I'm not able to create any shareable document as they come directly out of our HR system (SAP based) and contain sensitive data.

**Comment by stumpylog** [comment]
I would still suggest raising the issue up over there.  I believe at times they can get enough from metadata about the structure to find ways to resolve it.  (And by resolve it, I mean refuse to ingest these).  Or perhaps they can guide you to the necessary, not sensitive data, as it's not the data, but the structure of the file.

**Comment by shamoon** [comment]
Seems any progress on this would need to come from upstream, not here

**Comment by torwag** [comment]
Hmm.. The point is that all non-XFA compatible PDF engines (and that are basically all non Adobe engines)  get a PDF page to display, which simply points to using Adobe Acrobat.  Those engines which try to read XFA-based PDFs do so with horrible results usually.

I am not aware that one can easily figure out how to deal with it from the outside.  If the engine itself has a way, that would be, as @shamoon said, an inside job.
However,  that would lead to the point that the engine has to signal to the external application (paperless)  that it can't process that file.

Honestly, that entire XFA-based stuff is a mess.

The only valid way I found, is to open those in Adobe acrobat and print them via a PDF printer.
I have a container for doing so,  but unfortunately,  it seems Adobe Acrobat doesn't allow to script the printing process,  there are simply no flags on the command line to do so.

Alternatively,  make a lot of noise in your company (or from whom you get those pesty forms), explaining them that the format they use is not standard and already obsolete since many years.  That it does not keep the requirements for online archivability and that they might not be able to open their own forms in a few years if Adobe decides to completely stop the support.  Ask them to send PDF/A compatible PDFs instead.
I know it is a fight against windmills....  But every complain might help a bit.
