### ISSUE TITLE
[BUG] Confirmation dialog not closing after mass assign

### ISSUE THREAD

**Issue by bllngr** [paperless-ngx/paperless-ngx#1900]
### Description

The confirmation dialog for mass assigning tags/correspondents/document types etc. does not close after confirming the action.

### Steps to reproduce

1. On any view, select a number of documents
2. Change some property, like tags or correspondents using the "Edit:" fields
3. Apply the changes, and observe the confirmation dialog being opened
4. Confirm the mass changes using the respective button
5. Notice the properties being changed on-disk, but the dialog staying open
6. Press Cancel/Confirm again, and notice nothing happening
7. Close the dialog using the top-right `X`

### Paperless-ngx version

1.9.2

### Host OS

Synology DSM Version 7.1.1-42962 Update 2 

### Installation method

Docker - official image

### Browser

Firefox 106.0.1

### Configuration changes

`USERMAP_{U,G}ID, PAPERLESS_FILENAME_FORMAT, PAPERLESS_{FILENAME_,}DATE_ORDER, PAPERLESS_IGNORE_DATES`

**Comment by shamoon** [comment]
Sorry I cannot reproduce this (attached). My guess is theres something else, perhaps an error on the bulk edit that is causing it. Please check the container logs / browser logs as noted in the issue template, or if theres another way to reproduce let us know

**Comment by stumpylog** [comment]
I gave it a shot as well.  With 1k document and a complicated format which included the tags, correspondent and document type, I didn't see the dialog freeze either.

**Comment by mPolaczek** [comment]
I also had the error right after setting up Paperless. Now after 2 weeks in use the error no longer occurs, however the dialog closes slowly.

**Comment by ronstone2000** [comment]
I have seen this intermittently.

**Comment by ChrisMagnuson** [comment]
I have seen the same thing happen, select a group of documents, add or remove a tag, click confirm on the pop up and the pop up never goes away.

If I hit cancel or the x it looks like no changes have taken effect but if I refresh the page then I see the changes.

Hitting F12 in the browser and looking at the network tab in Chrome developer tools I can see that when this happens it is because there is a post to `/api/documents/bulk_edit/` that never receives a response and so the UI hangs waiting for the response to come back even though the call must have succeeded as the changes were made.

For me this happened when I was playing with different values for `PAPERLESS_TASK_WORKERS` and `PAPERLESS_THREADS_PER_WORKER` in the `paperless.conf` configuration file.

For certain configurations of those values after restarting the container I would have this issue and by playing with these values and restarting I would eventually get to a set of values that works without this issue popping up.

Currently I have both parameters set to `6` which has been stable for me.
