### ISSUE TITLE
[BUG] Concise description of the issue

### ISSUE THREAD

**Issue by ronstone2000** [paperless-ngx/paperless-ngx#1929]
### Description

I have two email accounts set up. One is with a local ISP and works as expected. Gmail does not. If I am reading the logs correctly, it connects successfully but never matches on criteria. 

### Steps to reproduce

ACCOUNT:
imap.gmail.com
993
SSL
email and app-password
UTF-8

RULE:
Account: gmail
INBOX
Filter from: <wife's email>
Max age: 300
Process all files, including 'inline' attachments.
Mark as read, don't process read mails
Use subject as title
Assign this document type: Personal
Assign this correspondent: <wife> (predefined)

### Webserver logs

```bash
(EMAIL FROM ADDRESS MASKED)
[2022-11-04 23:09:09,602] [DEBUG] [paperless_mail] Processing mail account gmail
[2022-11-04 23:09:10,731] [DEBUG] [paperless_mail] Account gmail: Processing 1 rule(s)
[2022-11-04 23:09:10,735] [DEBUG] [paperless_mail] Rule gmail.gmail test: Selecting folder INBOX
[2022-11-04 23:09:11,208] [DEBUG] [paperless_mail] Rule gmail.gmail test: Searching folder with criteria (SINCE 5-Oct-2022 FROM "xxxxxxxx@gmail.com" UNSEEN)
[2022-11-04 23:09:11,339] [DEBUG] [paperless_mail] Rule gmail.gmail test: Processed 0 matching mail(s)
[2022-11-04 23:09:11,340] [DEBUG] [paperless_mail] Rule gmail.gmail test: Running mail actions on 0 mails
```

### Paperless-ngx version

1.9.2

### Host OS

Raspian (Debian GNU/Linux 11 (bullseye))

### Installation method

Docker - official image

### Browser

Safari

### Configuration changes

PAPERLESS_ALLOWED_HOSTS="localhost,192.168.1.9"

**Comment by shamoon** [comment]
I’m not sure I see the bug exactly. Are you saying there are emails it should be processing but isn’t?

**Comment by ronstone2000** [comment]
Correct. I have tried with several simple filters, such from addresses copied from received mails with attachments. None has resulted in a match.

**Comment by shamoon** [comment]
Can you send your exact rule configuration? (Screenshot is fine)

**Comment by ronstone2000** [comment]
I've tried this with various filters, such as different email addresses or changing email address to a common word in the body. The logs always report 0 matches.

<img width="862" alt="Screenshot 2022-11-05 at 5 42 30 AM" src="https://user-images.githubusercontent.com/83873055/200113710-759a2f07-6de6-489f-81cf-1ba171b2eee0.png">

**Comment by shamoon** [comment]
Sorry, yea I cant reproduce this. I tried a few different ways. It looks like the login is working ok so presumably its an issue with the rule. Perhaps try creating a blank rule and just adding your changes one at a time. As long as I have an unread email this processes just fine.
<img width="992" alt="Screen Shot 2022-11-05 at 7 07 25 AM" src="https://user-images.githubusercontent.com/4887959/200123923-7a499a18-e664-43d9-a025-5dc0b6837d0e.png">
<img width="1432" alt="Screen Shot 2022-11-05 at 6 46 12 AM" src="https://user-images.githubusercontent.com/4887959/200123926-407149cf-138d-4832-a0c7-bb3a781465e7.png">
<img width="1379" alt="Screen Shot 2022-11-05 at 6 54 04 AM" src="https://user-images.githubusercontent.com/4887959/200123927-eedfa03c-fd1a-42d2-8016-91145e438f03.png">
<img width="1383" alt="Screen Shot 2022-11-05 at 7 00 20 AM" src="https://user-images.githubusercontent.com/4887959/200123928-abed75bc-af22-4b3d-bc7b-d065bc190dee.png">

The only other thing I noticed is your post says `SINCE 5-Oct-2022 FROM "xxxxxxxx@gmail.com" UNSEEN` which wouldn't correspond with the screenshot with a max age of 300 days, but perhaps the screenshot is just from a different time.

**Comment by ronstone2000** [comment]
Thanks for the advise.

I started again from scratch, matching against a new email and this worked. I may not have understood how this works earlier. Does Paperless-ngx mark emails that are not matched as 'seen', so that a new matching rule will skip them? 

By the way, still evaluating but so far impressed. Please keep up the good work.
