### ISSUE TITLE
[BUG] v1.9.0 RC1 Bug: Content in UI not updated after OCR redo

### ISSUE THREAD

**Issue by julienwetzel** [paperless-ngx/paperless-ngx#2024]
### Description

Hi !
Redoing OCR work at 50%.
When I redoing OCR, the server match good for metadata but the content view are not change.
My file are consumed before beta version and metadata not proposed, that correct.
![firefox_iDJrnKzwzf](https://user-images.githubusercontent.com/1897591/203389614-566dfd25-9519-4e77-9286-bc0c321e6ee9.png)

Now, I redoing OCR and propose metadata. That's good !
![firefox_oVLtTwrcRc](https://user-images.githubusercontent.com/1897591/203390010-1e0bb60c-970c-411e-a8d2-f9296e3d0042.png)

But, in the content view, not updated:
![firefox_w2xMUPuuS7](https://user-images.githubusercontent.com/1897591/203390331-7a2d3da1-7a14-4e41-b852-4c6daf32bf9b.png)
Logs:
![firefox_zcS9zcM6GK](https://user-images.githubusercontent.com/1897591/203391696-71e5079f-361b-43e3-bc9a-eebd8432320e.png)

But if I delete the file and reupload it, thats work:
![firefox_B5OiHB50xJ](https://user-images.githubusercontent.com/1897591/203390784-f98fcb38-985b-45d8-adc2-799eccb2211d.png)

### Steps to reproduce

Explain in the description

### Webserver logs

```bash
Description images
```

### Paperless-ngx version

Paperless-ngx 1.10.0-beta

### Host OS

Linux 7a74269e0c63 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 GNU/Linux

### Installation method

Docker - official image

### Browser

Edge, Firefox

**Comment by stumpylog** [comment]
I believe @shamoon is busy, but this looks like a frontend thing.  If a document is "open" when the OCR is re-done, the new (maybe) content won't be used in the Content tab until the document is re-opened.  Since there's maybe other changes, just closing the doc isn't a solution.

There's a simple work around though, trigger the redo through the main documents view.  Or if already done, close the document and don't save your changes (that could overwrite content)

**Comment by julienwetzel** [comment]
> I believe @shamoon is busy, but this looks like a frontend thing.  If a document is "open" when the OCR is re-done, the new (maybe) content won't be used in the Content tab until the document is re-opened.  Since there's maybe other changes, just closing the doc isn't a solution.
> 
> There's a simple work around though, trigger the redo through the main documents view.  Or if already done, close the document and don't save your changes (that could overwrite content)

Thank you, it works that way. 
I add that if we do re-done Ocr in edit mode, click on grayed cancel button in the content view.

**Comment by shamoon** [comment]
Yes, because OCR is asynchronously performed in the backend the frontend doesn't "know" when its complete. There are more complicated solutions but perhaps it would be enough to simply update the notification to something like "OCR started, you will need to close the document or refresh content after completion to see new OCR" (perhaps shorter than that).

Do we think that would be enough?

**Comment by stumpylog** [comment]
Yeah, I think that's enough.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/2140d4209825252bd9106ac9ade6dc1ba4e507dd

**Comment by julienwetzel** [comment]
Yes, but if we activate re-ocr in edit mode, refresh page or close the document does not refresh ocr content. To do this, we must click on the abort button.

**Comment by julienwetzel** [comment]
Instead, I propose a message that the edit mode will close without saving the changes. And this when you click on the re-ocr button. This action simulates the abort action which will refresh the ocr content.

**Comment by shamoon** [comment]
Actually in researching another issue I now understand why youre saying that. But rather than change it here (i.e. push into the beta) I would prefer we release that change separately to ensure it doesnt have other consequences. In other words, I'd like to leave this for now, knowing that a future change will make it a bit more straightforward
