### ISSUE TITLE
[BUG] Display of View and Edit permissions problem

### ISSUE THREAD

**Issue by jonaswinkler** [paperless-ngx/paperless-ngx#2810]
Issue:

I have a group, and two users in that group. Assigning just edit permissions to the group on a document, and then reopening results in the following:

![Image](https://user-images.githubusercontent.com/17569239/222853790-a77dea65-c74d-49a8-a635-2bf52b54de66.png)

This is when logged in as "superuser".

* the tag of "superuser" seems messed up.
* Just entering work as the group in edit populates all this data. It is technically correct, when I give edit permissions to a group, then these are the implied permissions (edit for the users of the group, and view permissions for the group and its users). However I wouldn't expect them to show up here, since I did not explicitly configure anything expect editing for the group "work".

**Comment by shamoon** [comment]
So the linked PR should fix the screenshot which is because the list was including the current user when they were in a group, so it shouldn't.

But there is another part to this question in how groups work, yes currently when you assign a group those other perms / users get assigned. If that's an issue we might need to dig into Django guardian a bit and see what we can do, tbh I don't recall if this is a deviation from how object-level perms inheritance works usually

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/62e756a11ec6d2bc4282d10320bb2924a0cd9c40
