### ISSUE TITLE
[BUG] install script does not create a working tika configuration for arm (raspberry pi)

### ISSUE THREAD

**Issue by tobiasschuerg** [paperless-ngx/paperless-ngx#363]
**Describe the bug**
The install script does not create a working docker-compose configuration with tika for arm (raspberry pi)

**Expected behavior**
Install script should also ask if architecture is arm
https://github.com/paperless-ngx/paperless-ngx/blob/a6d2a390f024fe4fe04de135431a77efef0faea0/install-paperless-ngx.sh#L123

and then use `image: abhilesh7/apache-tika-arm` and set `PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000/forms/libreoffice/convert#`

See https://github.com/jonaswinkler/paperless-ng/issues/1499#issuecomment-1037527276

**Comment by qcasey** [comment]
Thanks for reporting. Related: #27

**Comment by s-martin** [comment]
PR is now #479

**Comment by shamoon** [comment]
https://github.com/paperless-ngx/paperless-ngx/commit/5065f2cb80fbfc84f5e9a5219c8cafc716573e89

**Comment by iwishiwasaneagle** [comment]
Why was this bug closed? #479 didn't address this issue.

**Comment by shamoon** [comment]
My bad

**Comment by qcasey** [comment]
@iwishiwasaneagle for the sake of consistency, do you mind if we bring/fork your [tika-docker](https://github.com/iwishiwasaneagle/tika-docker) under the paperless-ngx org? Since your image builds all 3 archs, my thinking is it'd be easier to solve this issue by changing `image: apache/tika` to `image: paperless-ngx/tika`. Bringing it under the org would guarantee longevity and clarify the source. 

We could then get rid of [docker/compose/docker-compose.sqlite-tika.arm.yml](https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.sqlite-tika.arm.yml) and close this issue.

**Comment by iwishiwasaneagle** [comment]
> @iwishiwasaneagle for the sake of consistency, do you mind if we bring/fork your [tika-docker](https://github.com/iwishiwasaneagle/tika-docker) under the paperless-ngx org? Since your image builds all 3 archs, my thinking is it'd be easier to solve this issue by changing `image: apache/tika` to `image: paperless-ngx/tika`. Bringing it under the org would guarantee longevity and clarify the source.
> 
> We could then get rid of [docker/compose/docker-compose.sqlite-tika.arm.yml](https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.sqlite-tika.arm.yml?rgh-link-date=2022-05-01T23%3A20%3A42Z) and close this issue.

Sounds good. Would you like me to create a clean repo or tranfer ownership? Can create a PR for this as well.

**Comment by qcasey** [comment]
Thank you! I think a fork is fine. I've set that up already at [paperless-ngx/tika](https://github.com/paperless-ngx/tika) (which you have access to). 

I created a PR utilizing the new repo, which will fix this issue.

**Comment by iwishiwasaneagle** [comment]
Okay great. Anything you need me to do?

-------- Original Message --------
