### ISSUE TITLE
[BUG] Mail rules not loading

### ISSUE THREAD

**Issue by N1c093** [paperless-ngx/paperless-ngx#4009]
### Description

My users only have the rights to see/edit the mail rules and not the mailaccount. Since 1.17 the webpage mailsettings is not loading anymore. Only the loading animation is shown
![image](https://github.com/paperless-ngx/paperless-ngx/assets/59510296/082733f1-bb8d-4444-8161-e834df07c58f)

In Chrome DevTools I see this error:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/59510296/f604e590-7fad-4e71-8b6e-4a79b44ac661)

My users have the following permissions:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/59510296/d0f1f820-00b3-4a60-b45d-7bb88ca060db)

When the user have at least the permission to also view the mailaccount, the settings page is loading sucessfully

Maybe this problem is related to https://github.com/paperless-ngx/paperless-ngx/pull/3869

### Steps to reproduce

1. Give a user the permissions to administrate the mail rules. ( no permission to mailaccount) See example above
2. Login as the user with permission to administrate the mail rules
3. Open the mail settings.
4. See endless loading screen (example above)

### Webserver logs

```bash
Sorry, but where can I found the web server logs?
```

### Paperless-ngx version

1.17.0

### Host OS

Synology OS x86_64

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
The user will need to have at least 'view' privileges on mail accounts, this is necessary since of course mail rules take a mail account as one of their parameters

I can confirm that with permissions as such this works as expected, see below (I did notice the add button should be hidden, but thats obviously not the issue here, and it wouldn't actually work anyway)

<img width="1422" alt="Screenshot 2023-08-17 at 1 33 24 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/a0c71b12-6faf-4663-889c-328089de227d">

**Comment by N1c093** [comment]
Thank you for your explanation. That really makes sense. I was just wondering, because it worked that way before 1.17.0

I just gave my users the mail accounts permissions and everything is working fine :)
