### ISSUE TITLE
[BUG] Selecting a filter will not show anything if called current page number > #pages to be shown

### ISSUE THREAD

**Issue by pop-ch** [paperless-ngx/paperless-ngx#4011]
### Description

In some circumstances: selecting any of the criteria for filtering documents will just show the busy icon and will not show any result at all. This occurs when you're currently on a page number in the documents view which is larger than the number of pages for the selection result. I.e.: when the number of documents shown on a page is 50, you're on page# 2 or larger in the document view and your query returns 50 or fewer documents.

### Steps to reproduce

Go to the documents view.
remove all filtering criteria.
go to any page but the first one.
select a filtering criterium (such as document type or correspondent) for which the page number of the last result page is less than the number of the currently shown page

This will only show the busy indicator; no result will ever appear.

### Webserver logs

```bash
none
```

### Paperless-ngx version

1.17.1

### Host OS

Ubuntu 22.04.3 LTS

### Installation method

Docker - official image

### Browser

Firefox Browser 116.0.1 (64-Bit)

**Comment by shamoon** [comment]
This has come up in the past https://github.com/paperless-ngx/paperless-ngx/issues/2487 https://github.com/paperless-ngx/paperless-ngx/issues/1819 and I have never been able to reproduce it, and you can see below I still cannot.

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/71a878e6-aa72-49a1-99e7-6b68c3ae716f

As noted in those threads, the frontend has explicit code to handle this since, of course, it is a pretty common situation.

https://github.com/paperless-ngx/paperless-ngx/blob/d94ca2962ebe2758b80d9deae01a20953f0edc46/src-ui/src/app/services/document-list-view.service.ts#L245-L248

Besides that, I dont see how we would fix this short of putting some kind of timeout in place. But of course thats not a good solution since it would have to be relatively long (30s?) and it would be a similarly unpleasant user experience.

The other possibility would be to always just revert to page 1 when filtering, but I feel that is not ideal either.

It would be worth checking what the API response is for the call that _should_ fail, the one I highlight in the video something like `http://localhost:8000/api/documents/?page=2&page_size=50&ordering=-added&truncate_content=true&correspondent__id__in=17`, fundamentally if theres a way to mitigate this somehow it would be there. But again, I cannot even reproduce it, that call properly returns a 404 for me.

**Comment by pop-ch** [comment]
The technical side of this is way above my head. I don't speak JavaScript. However, I agree that adding a timeout would not improve the user experience at all.
On the conceptual side I can add these comments:
(1) The page we're on when adding (additional) selection criteria is in most cases quite meaningless. I could see where it would make sense to conserve this position when the selection would truncate the former selection from the end. That would not be a common occurrence, I believe. 
(2) I rather think that simply positioning the cursor at the beginning of the selection would seem sensible to most users in most cases.
(3) To add extra eye candy, you could store the current position before applying new criteria and pop it back when the filter is cleared.
(4) As a kind of compromise you could reset the cursor to the start of the set when the current cursor points beyond the end of the new selection. However, I don't know if it's possible to know the size of the result set.

**Comment by pop-ch** [comment]
Just tested this with different user agents. Even Opera and Edge on Windows 10 produce the error.

**Comment by shamoon** [comment]
Now that I think about it, it's not so simple anyway, there is no way to 'know' whether a user just clicked to change filters or if they are intentionally navigating to page > 1, thats why the code is written as such to catch a 404 and if page > 1, try again with page = 1, its an 'educated guess'.

Again:

- Opening that API url should throw a 404 as I noted above. Really this should apply to any URL with a page index out of range (eg `http://localhost:8000/api/documents/?tags__id__in=2&page=999999`). It would be worth trying this, as I mentioned. There may be a more specific situation at hand.
- This doesnt have anything to do with browser, perhaps it could be somehow deployment-specific. That said, you and I are running similar setups and I can't reproduce.

**Comment by shamoon** [comment]
https://github.com/encode/django-rest-framework/blob/40eccb0d6cdb769876dbb79724c5871b4f04163d/rest_framework/pagination.py#L211-L217
