### ISSUE TITLE
[BUG] alternative database password does not work

### ISSUE THREAD

**Issue by nillebor** [paperless-ngx/paperless-ngx#4200]
### Description

I made a database upgrade (postgres16) yesterday and made a few more changes after that. I noticed that no other database password is accepted. no matter how long, short with numbers or special characters. Only the original password "paperless" works. The database, users and containers have also been recreated. Paperless always reports an incorrect password.

`django.db.utils.OperationalError: connection to server at "postgres" (172.18.0.5), port 5432 failed: FATAL:  password authentication failed for user "paperless"`

i don't think it's because of postgres 16. After changing the password, paperless works again. Of course, if only the password is changed in postgres, the error will also occur. The error occurs as soon as the default password is changed.

Any idea?

### Steps to reproduce

1. change password in postgres
2. change password in paperless- container
3. start paperless

### Paperless-ngx version

latest

### Host OS

DSM 7.1.1 Update 6

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

Docker environment (Container)

**Comment by nillebor** [comment]
> ### Description
> 
> I made a database upgrade (postgres16) yesterday and made a few more changes after that. I noticed that no other database password is accepted. no matter how long, short with numbers or special characters. Only the original password "paperless" works. The database, users and containers have also been recreated. Paperless always reports an incorrect password.
> 
> `django.db.utils.OperationalError: connection to server at "postgres" (172.18.0.5), port 5432 failed: FATAL:  password authentication failed for user "paperless"`
> 
> i don't think it's because of postgres 16. After changing the password, paperless works again. Of course, if only the password is changed in postgres, the error will also occur. The error occurs as soon as the default password is changed.
> 
> Any idea?
> ### Steps to reproduce
> 
>     1. change password in postgres
> 
>     2. change password in paperless- container
> 
>     3. start paperless
> 
> ### Paperless-ngx version
> 
> latest
> ### Host OS
> 
> DSM 7.1.1 Update 6
> ### Installation method
> 
> Docker - official image
> ### Browser
> 
> Firefox
> ### Configuration changes
> 
> Docker environment (Container)

**Comment by stumpylog** [comment]
Make sure you recreate the container.  Restarting doesn't apply new environment variables.

**Comment by Flightkick** [comment]
Not OP, but just to document a possible edge-case.

This was a pretty dumb one on my side. I got the same error regarding auth failures popping up in my application and the database logs. Turns out I duplicated the docker-compose environment because I needed an extra instance, but I forgot to migrate the cloned instance to it's own network. The app from instance 1 was trying to connect to the DB host from instance 2 and vice versa.

I'm very grateful that psycopg2 properly wraps underlying error messages and that psql includes the hostname and IP because this allowed me to debug why the application failed to connect to that specific address through docker network inspect.
