### ISSUE TITLE
Import via document_importer compains about lacking files with umlauts that are referenced in the manifest.json

### ISSUE THREAD

**Issue by LordMyschkin** [paperless-ngx/paperless-ngx#4485]
### Description

I tried to export my documents via document_export; some files with umlauts in their names.
when trying to import them back into the clean database, paperless complains about file in the manifest.json but not in the source directory and exits without having imported anything.

exact error is: 
`The manifest file refers to "2023-07-19 Überlassung Businessbike.pdf" which does not appear to be in the source directory.
`

### Steps to reproduce

export a database with german umlauts

try to import them into a new database

### Webserver logs

```bash
the web server does not log anything then running that command.
```

### Paperless-ngx version

1.17.4

### Host OS

rasbian os bookworm 64 Bit 

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Perhaps this is OS specific, but no issues here

```bash
python3 manage.py document_exporter ../export
100%|███████████████████████████████████████| 1/1 [00:00<00:00, 443.89it/s]
```

```bash
ls -a ../export
2023-11-01 Überlassung Businessbike.pdf				manifest.json
2023-11-01 Überlassung Businessbike.pdf-archive.pdf		version.json
2023-11-01 Überlassung Businessbike.pdf-thumbnail.webp
```

...

```bash
document_importer ../export
Checking the manifest
Installed 152 object(s) from 1 fixture(s)
Copy files into paperless...
100%|███████████████████████████████████████| 1/1 [00:00<00:00, 237.30it/s]
Updating search index...
100%|███████████████████████████████████████| 1/1 [00:00<00:00, 198.53it/s]
```

```bash
ls ../media/documents/originals
2023-Überlassung Businessbike.pdf
```

**Comment by shamoon** [comment]
Did you check if `"2023-07-19 Überlassung Businessbike.pdf"` is in the export folder?

**Comment by LordMyschkin** [comment]
it sure is, as many other similiar documnets with Umlauts in their name which do not get imported...
Maybe the problem is not the umlauts, but anything else? I assume the manifest.json and the documents are supposed to be in the same directory, and if the manifest is readable, the docs also should be - so a permission issue seems unlikely....

Adding a Document by web UI works, so paperless-ngx is functional.

I thought about replacing the escaped umlauts in the manifest  through their original- maybe it's the way they are converted  in the manifest and re-escaped ?

**Comment by NoxObscuro** [comment]
There is a Unicode character class of multibyte characters for example the combining diaeresis (U+0308) which can be used in combination with another character e.g., a simple “U” to create an umlaut or similar instead of using the actual Unicode character in this case Ü (Latin Capital Letter U with Diaeresis, U+00DC). 
It might be one of the used libraries that uses the multicharacter encoding approach in favor of the single character representation. It could also be a combination of the browser and/or the file system or even the database encoding. More information needed.
The previous posts in this issue essentially describe the same situation I encountered on an macOS system which hosted a single user paperless instance. The manifest contains the multicharacter variant of the umlaut “Ü” while the filenames use the singlecharacter variant. You will see the same thing if you compare the umlaut in the manifest error line in https://github.com/paperless-ngx/paperless-ngx/issues/4485#issue-1973338982 with the umlauts in the ls output in https://github.com/paperless-ngx/paperless-ngx/issues/4485#issuecomment-1790373885. You can copy the respective umlaut and paste it into a textarea and press backspace once to notice the difference.
The aforementioned macOS instance doesn't exist anymore, so I cannot inquire further, but maybe this can be of help.

**Comment by LordMyschkin** [comment]
thanks, @NoxObscuro, you pointed me onto the right track. after changing the umlaut-encoding in two of my filenames in the manifest.json (AND after deleting the user those documents where saved) I coud reimport all my 184 documents.
I leave that open here - i have no idea why in two files the program chose that encoding (and in many others, id didn't) - but I sure prevents from restoring the backup, and it's sure worth a change in the document_exporter module.

**Comment by dominicpratt** [comment]
I had exactly the same problem yesterday and solved it by removing the umlaut from the document title and re-exporting the documents.

Just for the record ;)

**Comment by shamoon** [comment]
Stumpylog was kind enough to look into this (not my wheelhouse) and as you'll see the linked PR should force utf-8 encoding. If anyone experiencing this (we aren't) would like to test this you can use the `dev` image, but I wouldn't recommend doing that on a production install, just as a test thing.

**Comment by LordMyschkin** [comment]
I'll have to set up my old environment again, but I should be able to check on that 'til sunday

**Comment by LordMyschkin** [comment]
At least I can confirm that my documents export and import properly now on version 2.0.1 - lost my backups of my former setup, so I am not sure about 1.7.4
