### ISSUE TITLE
[BUG] advanced searching for created date gives bad results

### ISSUE THREAD

**Issue by akumiszcza** [paperless-ngx/paperless-ngx#4741]
### Description

Searching for created date in the format "created:20231119" shows documents created one day later.
<img width="640" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/52917795/1e586f2a-cdd2-48c5-8112-ee7ee64f3efc">

### Steps to reproduce

1. Go to Documents
2. Switch to Advanced search
3. Put "created:<date>" (without hyphens as per https://whoosh.readthedocs.io/en/latest/dates.html#parsing-date-queries)
4. All the results have created date one day later.

### Webserver logs

```bash
no logs
```

### Paperless-ngx version

2.0.1

### Host OS

Unraid (Linux)

### Installation method

Docker - official image

### Browser

Brave (Chrome)

### Other

CET timezone if relevant (UTC+1:00).

**Comment by stumpylog** [comment]
I'm pretty sure that doesn't use Whoosh, but the database.  Which isn't going to be incorrect.

**Comment by akumiszcza** [comment]
> I'm pretty sure that doesn't use Whoosh, but the database. Which isn't going to be incorrect.

According to this it uses whoosh: https://docs.paperless-ngx.com/usage/#basic-usage_searching

**Comment by stumpylog** [comment]
I also cannot reproduce this.  created and added match to the documents' values.

**Comment by akumiszcza** [comment]
Easier way to reproduce: just use last month in created drop-down menu.
<img width="188" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/52917795/b46140c1-f59f-4152-b46d-9ad0f41ba9cd">

The results include 2023-12-01 (today), but exclude 2023-11-01.

**Comment by akumiszcza** [comment]
Well, you can see the screenshot above. And I've just reproduced in on another computer with another browser. 
What data is needed to understand what's happening? Any logs I can upload here?

**Comment by shamoon** [comment]
My assumption is the problem is your timezone in the browser or the OS, so the documents do have that date but in the browser the date is getting timezone-ified so it looks wrong to you.

What does that search look like against the api (look in the browser console and open the url like /api/documents/... )

But no, I cant reproduce this
<img width="361" alt="Screenshot 2023-12-01 at 4 46 16 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/a8956e99-1bc6-4b11-b058-870579167204">

**Comment by akumiszcza** [comment]
I used date(Linux) and time(Windows) commands on consoles of Unraid, paperless docker and my Windows system to confirm the time and timezone is the same everywhere. It's the same on all my computers, too. The PAPERLESS_TIME_ZONE is also correct.

I also tried setting different languages and time formats in paperless-ngx. The error still appears.

**Comment by shamoon** [comment]
From above:

> What does that search look like against the api (look in the browser console and open the url like /api/documents/... )

**Comment by akumiszcza** [comment]
<img width="600" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/52917795/51ef691b-c029-472d-a2bf-5280b18f4e59">

**Comment by akumiszcza** [comment]
And here's my environment settings in docker:
<img width="691" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/52917795/9456db95-82fa-47ad-b981-42ef8a8aa200">

**Comment by shamoon** [comment]
Have you tried reindexing? https://docs.paperless-ngx.com/administration/#index

**Comment by akumiszcza** [comment]
I used document_index reindex and then document_index optimize on console, then restarted the docker. Same error.

**Comment by shamoon** [comment]
I dunno, thing is the code for this is basically straight using whoosh:

https://github.com/paperless-ngx/paperless-ngx/blob/20f27fe32ffe144813d6c69e3326bf230a2da52a/src/documents/index.py#L374-L375

As noted:

- Neither of us can reproduce this, nor with a test
- No one else is reporting it
- We didnt intentionally change anything to do with this
- whoosh hasn't been touched in a while https://github.com/mchaput/whoosh

My guess is theres an alternate explanation, but otherwise I dont see where this is actionable for us, unfortunately.

**Comment by Finkman** [comment]
I believe it is similar to mine:
![Bildschirmfoto vom 2023-12-08 12-19-16](https://github.com/paperless-ngx/paperless-ngx/assets/12600527/592d0205-347f-4cbf-91f2-96163f856a7c)
First row makes no sense to me.

**Comment by bogdal** [comment]
This problem occurs since, all document dates are indexed in their UTC representations. I have added more details [here](https://github.com/paperless-ngx/paperless-ngx/pull/4891).
