### ISSUE TITLE
[BUG] Date of document does not work

### ISSUE THREAD

**Issue by mabushey** [paperless-ngx/paperless-ngx#4822]
### Description

When a document is imported, the date is either today or random. Is there any way it could be parsed from the document itself? Right now after importing documents I have to go through each one to set the ie invoice/statement date.

### Steps to reproduce

1. Import document

### Webserver logs

```bash
--
```

### Browser logs

```bash
--
```

### Paperless-ngx version

2.0.1

### Host OS

Linux monor 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

Docker - official image

### Browser

Chromium

**Comment by stumpylog** [comment]
Dates are already parsed from documents.  You can see in the debug logs where the date is chosen from.

In the future, please use a discussion first.  As the template says, issues are for things which affect every user.  A simple question like this is not an issue.

**Comment by mabushey** [comment]
The log in the app is pretty defective, it doesn't allow scrolling.  Does anyone know of an open source document management system that can read the date from the document?

**Comment by mabushey** [comment]
@stumpylog
You mean "A simple **bug** like this is not an issue". To me it's a show-stopper as I would like to set up a system where my scanner can send directly to the consume dir and have the system parse it with the correct tag (matching words does work, the AI default appears to not be implement yet or requires a certain amount of documents first) and date on the document.

**Comment by stumpylog** [comment]
Again, as stated, the date is read from the content of the document.

The log 100% scrolls as necessary:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/797416/b5194904-dcbd-4205-a536-18403e85276b)

**Comment by shamoon** [comment]
I find date parsing generally works well but the documentation does note it’s not perfect. This is not a bug in the sense that you’re kind of just unhappy with how it works, which I might add is just your opinion. There is no error being generated, there isn’t even enough information here to be able to reproduce anything , I mean look at your “steps” and logs above…

Respectfully, this is open source software made by people using their not-so-free time, if you want to go find a commercial system that is more to your liking that’s fine, otherwise you should think of this as a collective effort
