### ISSUE TITLE
[BUG] Running export command prints to std err, not stdout

### ISSUE THREAD

**Issue by oregonpillow** [paperless-ngx/paperless-ngx#5003]
### Description

Running an export command using docker exec prints to stderr, NOT stdout. Should write to stdout if export success.

### Steps to reproduce

```
$ docker compose  exec   -T webserver document_exporter   --delete ../export 2>/dev/null
$ docker compose  exec   -T webserver document_exporter   --delete ../export >/dev/null
100%|██████████| 171/171 [00:00<00:00, 5587.05it/s]
```

### Webserver logs

```bash
N/A
```

### Browser logs

```bash
N/A
```

### Paperless-ngx version

2.1.3

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

N/A

### Configuration changes

N/A

**Comment by stumpylog** [comment]
Perhaps you can expand on why you think this is a bug, not merely something you didn't expect or would like to see change (perhaps to fit some workflow)

**Comment by stumpylog** [comment]
At best, it seems to me like a feature request.  Writing the progress bar to stderr is expected and deliberate, since most tools, etc would be looking at stdout for actual messages, not a rapidly changing, not helpful for a tool, value.

If you don't like the progress bar or are using some wrapper for the command, just disable it with `--no-progress-bar`
