### ISSUE TITLE
lost translation german

### ISSUE THREAD

**Issue by muecke6** [paperless-ngx/paperless-ngx#5149]
### Description

no bug but in version 2.2.1 the translation to german has been lost in the menu

Notes ----> Notizen
File Task ----> Dateiaufgaben

attached screenshot
![filetask2](https://github.com/paperless-ngx/paperless-ngx/assets/123741690/a39ec56e-8f36-4546-bff9-dee9a5db7186)
![notes](https://github.com/paperless-ngx/paperless-ngx/assets/123741690/234e755f-0052-4281-bfc9-125495630f6c)
![filetask1](https://github.com/paperless-ngx/paperless-ngx/assets/123741690/c187d0cc-37e8-4dce-a648-78e7e0f38122)

### Steps to reproduce

go to menu

### Webserver logs

```bash
no
```

### Browser logs

```bash
no
```

### Paperless-ngx version

2.2.1

### Host OS

Synology NAS

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Thanks. Some of the translation strings moved from unrelated changes. I'm not sure why a couple of translations didnt get included in the last version of the files generated by crowdin, but they look to be in the currently open PR for that: #5146

e.g. 
https://github.com/paperless-ngx/paperless-ngx/blob/321aed6409198b4c7b9ba3185dc7ba25f54e6652/src-ui/src/locale/messages.de_DE.xlf#L1687-L1692

So that will be included in our next release.

**Comment by wavyfuncollaps** [comment]
Problem is with other languages too. I tried to fix it in my dev env. The reason seems to be the dynamic part inside the nav-link: `File Tasks@if (tasksService.failedFileTasks.length > 0 && slimSidebarEnabled)`

In my dev environment this works for the "File Tasks" menu button:
`<li class="nav-item"
            *pngxIfPermissions="{ action: PermissionAction.View, type: PermissionType.PaperlessTask }"
            tourAnchor="tour.file-tasks">
            <a class="nav-link" routerLink="tasks" routerLinkActive="active" (click)="closeMenu()"
              ngbPopover="File Tasks" i18n-ngbPopover [disablePopover]="!slimSidebarEnabled" placement="end"
              container="body" triggers="mouseenter:mouseleave" popoverClass="popover-slim">
              @if (tasksService.failedFileTasks.length > 0 && slimSidebarEnabled) {
                <span class="badge bg-danger position-absolute top-0 end-0">{{tasksService.failedFileTasks.length}}</span>
              }
              <svg class="sidebaricon" fill="currentColor">
                <use xlink:href="assets/bootstrap-icons.svg#list-task" />
              </svg><span>&nbsp;<span i18n>File Tasks</span>
              <span *ngIf="tasksService.failedFileTasks.length > 0" class="badge bg-danger ms-2">{{tasksService.failedFileTasks.length}}</span>
            </span>
            </a>
          </li>`

and in the messages.xlf
`      <trans-unit id="2991443309752293110" datatype="html">
        <source>File Tasks</source>
        ...
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/components/app-frame/app-frame.component.html</context>
          <context context-type="linenumber">303</context>
        </context-group>
      </trans-unit>`
