### ISSUE TITLE
[BUG] Import messages overlap the GUI

### ISSUE THREAD

**Issue by Vertux** [paperless-ngx/paperless-ngx#5466]
### Description

If you import documents, the information messages about the successful import overlap the user interface.
<img width="329" alt="Bildschirmfoto 2023-12-22 um 22 12 18" src="https://github.com/paperless-ngx/paperless-ngx/assets/10457918/48e9a5c8-d1c0-466b-92c7-1417512daed9">

### Steps to reproduce

1. Just import a couple of documents.

### Webserver logs

```bash
none
```

### Browser logs

```bash
none
```

### Paperless-ngx version

2.1.3

### Host OS

Debian 12.x x86_64

### Installation method

Docker - official image

### Browser

 Firefox 121.01  (macOS)

### Configuration changes

None

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Everything UI is a compromise, Im not sure theres an obvious solution at the moment but this isnt unintentional.

**Comment by shamoon** [comment]
You can open a feature requrest or change request. I do consider the UI a priority, I obsess over it actually, just not a bug because it was an intentional compromise. Also, UI design esepcially on the web on variable screens is definitely always a compromise.

I think you'll find the real reason issues dont stack up is because we are fastidious about triaging and resolving them. Change requests fall under discussions and we roughly use that to decide where to focus our efforts. Sorry if that isnt clear, we try to make this clear in the issue template.

**Comment by shamoon** [comment]
I rarely do this, but your comment has such a level of ingratitude and ignorance I cant help it. Particularly I take issue with:

1. Implying we dont care about the UI or something like that. Look at the history of this project. For the amount of time we spend, this is just inaccurate and offensive.
2. Implying there are few open issues here for any reason other than the fact that we dedicate huge amounts of time to it.
3. Implying that you somehow know how we (or anyone) should be maintaining this project.

Feel free not to reply, Im really not trying to be obnoxious here but this is open source software that you enjoy for free, please remember that.
