### ISSUE TITLE
[BUG] No matching manifest for linux/arm/v7, when installing on Rasperry Pi 4 

### ISSUE THREAD

**Issue by s-martin** [paperless-ngx/paperless-ngx#5586]
### Description

As described in https://github.com/paperless-ngx/paperless-ngx/discussions/4726 I tried to run latest version on a RaspberryPi 4, which actually uses 64 bit ("uname -m" --> "aarch64"), but on `docker-compose pull` I get the error `ERROR: no matching manifest for linux/arm/v7 in the manifest list entries`.

The as "answered" marked answer of the issue #4726 references an issue of the Raspberry project (https://github.com/raspberrypi/linux/issues/5402), which suggests that the check used by paperless-ngx, if running on a 64 bit version might actually be not correct.  `dpkg --print-architecture` still returns `armhf`.

Unfortunately this answer does not fix the problem.

### Steps to reproduce

1. Run installation script on a Raspberry 4 with 64 bit enabled
2. Run `docker-compose pull`

### Webserver logs

```bash
not possible as installation doesn't succeed
```

### Paperless-ngx version

2.4

### Host OS

Raspberry Pi Bullseye 64 bit

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This is not a bug.  ARMv7 support was dropped for v2.  That was its major breaking change.

**Comment by s-martin** [comment]
Okay, but my Pi 4 is an ARMv8. So shouldn't it work then? Or were other ARM versions dropped as well?

https://www.raspberrypi.com/products/raspberry-pi-4-model-b/specifications/

**Comment by stumpylog** [comment]
If you actually read https://github.com/raspberrypi/linux/issues/5402 it would be clear.  Your OS is not 64 bit, even if the processor is.

**Comment by Rory-Lambert** [comment]
Hi, encountering the same issue as s-martin above. Apologies, but can you clarify? As I understand it, in version 2.0 of paperless-ngx 32bit support was dropped? I think this was the architecture of Raspberry Pis 3 and below. But the raspberry pi 4B architecture is ARMv8 64 bit and there are [64 bit OS's available](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit). Is the problem not that the rpi self-reports the wrong architecture [(as per) error 5402 ](https://github.com/raspberrypi/linux/issues/5402). 

> Check the architectures again: "uname -m" now gives aarch64. "dpkg --print-architecture" still reports armhf.

So paperless' install script is trying to install a 32bit version because thats what the rpi is saying it is?

Anyway, thanks for this great software and all your hard work on it. I runs perfectly on my desktop and the installation process there was incredibly smooth.

**Comment by Johnnii360** [comment]
Same issue here. My Pi 4B is clearly ARMv8 and run 64-Bit OS! It looks more like the dev is to lazy to investigate or find a solution. And please don't argue with "it's free so pay me for better service or get lost" because this is also lame.
