### ISSUE TITLE
[BUG] Save button is deactivated first and need two clicks to work

### ISSUE THREAD

**Issue by fantasticle** [paperless-ngx/paperless-ngx#569]
**Describe the bug**
This is new to me. I was updating a batch of newly imported documents and when going through them I noticed that the "save"-Button is deactivated first and will only activate after 1-2s when I change the title or a second click when I change the date.

**To Reproduce**
1. Click on a document to edit it.
2. Try saving right now => nothing has changed - nothing to save. (makes sense)
3. Change the date. 
4. Save button is still greyed out.

**Expected behavior**
I expect every cell to be instantly evaluated so that I can go through my files without double-clicking or time delay.

**Screenshots**

https://user-images.githubusercontent.com/84633558/160777802-5ae0f6ff-94fa-452a-9b67-29fe242d956c.mov

**Relevant information**
 - Ubunt 20.04 LTS, 2 CPU, 4 GB RAM, vServer
 - paperless-ngx 1.6.0
 - docker-compose
```
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_SECRET_KEY=my_secret_key
PAPERLESS_FILENAME_FORMAT={correspondent}/{created_year}_{title}
PAPERLESS_OCR_OUTPUTE_PAGES=False
```

**Comment by shamoon** [comment]
Thanks for the report but that is happening because you havent left the field yet so the change isnt registered. It makes sense for fields where the user types, like that and the title. You'll notice fields where you click like the tags dont have this delay.

There are also some improvements to this in the next release.

**Comment by fantasticle** [comment]
> Thanks for the report but that is happening because you havent left the field yet so the change isnt registered. It makes sense for fields where the user types, like that and the title. You'll notice fields where you click like the tags dont have this delay.
> 

Hi shamoon,
thank you for the reply. From a UX point of view, how does the extra click make sense? Wouldn't it make be better to register the current input (which is happening for the other fields as far as I can tell anyway) and check if there's a difference? As soon one is recognized the save button gets enabled. My view might be biased though because I personally change dates (and nothing else) quite often and so the extra click is noticeable ;-)

> There are also some improvements to this in the next release.
I'm happy to hear that! It's a joy to see paperless-ngx gaining such momentum!

**Comment by shamoon** [comment]
The short answer is that date parsing is complex, when the keyboard is used for the date field a lot of magic happens in the background with converting it, detecting the correct date, etc. So while the title has a debounce to automatically detect changes, it would be problematic here because someone might be in the middle of entering the date, etc.

If you use the date picker buttons its automatic, of course. Otherwise you need to have the date input field lose focus, i.e. click outside of it or even just tabbing to another field.

It is not so much a choice "from a UX point of view", but more of a compromise =)
