### ISSUE TITLE
System Status shows classifier error after update 2.6.0

### ISSUE THREAD

**Issue by Flol0** [paperless-ngx/paperless-ngx#6007]
### Description

In System Status, i get an Error on the Classifier Status.

### Steps to reproduce

1. Go to Settings
2. Click on System Status

### Webserver logs

```bash
[2024-03-05 06:55:47,456] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/views.py", line 1625, in get
    raise Exception("Classifier not loaded")
Exception: Classifier not loaded
```

### Paperless-ngx version

2.6.0

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I mean, this is telling you theres an error with the classifier. Have you looked into whether thats accurate or not?

**Comment by shamoon** [comment]
Im inclined to think this is doing what its supposed to, all it does is try to load the classifier:

https://github.com/paperless-ngx/paperless-ngx/blob/04af29083b660ffcfb26716b1aad83b2b2f108e5/src/documents/classifier.py#L39-L70

Feel free to clarify if otherwise

**Comment by tom666-debug** [comment]
I am experiencing the same issue as described by [Flol0](https://github.com/Flol0):

![Screenshot 2024-03-05 075304](https://github.com/paperless-ngx/paperless-ngx/assets/78903224/72692efd-3bfa-4776-816d-a200162e0319)

Webserver-log:
[2024-03-05 07:21:03,381] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/views.py", line 1625, in get
    raise Exception("Classifier not loaded")
Exception: Classifier not loaded

[shamoon](https://github.com/shamoon): whats the meaning of "_Im inclined to think this is doing what its supposed to, all it does is try to load the classifier_"? We can see clearly an error within the GUI and the logfile as well. I am not sure what to do now, ignore the error and wait for a fix?

**Comment by jxtxzzw** [comment]
Same issue here. I do agree this is a bug.

Did some investigation on my side, I think if you wait around 10 minutes, the ERROR should be gone and System Status will give you all green marks.

I think the issue here is, before 2.6.0, when Paperless gets loaded, it takes some time to train and update the classifier model. On my server, it takes around 6-7 minutes.

```
[2024-03-05 15:06:36,804] [DEBUG] [paperless.classifier] Training correspondent classifier...
[2024-03-05 15:06:52,847] [DEBUG] [paperless.classifier] Training document type classifier...
[2024-03-05 15:07:04,983] [DEBUG] [paperless.classifier] Training storage paths classifier...
[2024-03-05 15:07:10,730] [INFO] [paperless.tasks] Saving updated classifier model to /usr/src/paperless/data/classification_model.pickle...
```

And in a real word, when people need to use classifiers, Paperless will call `load_classifier()` and we can get that classifier.

However in 2.6.0, due to the period check of System Status, it calls `load_classifier()` in the first few minutes and it can't get the classifier: https://github.com/paperless-ngx/paperless-ngx/blob/04af29083b660ffcfb26716b1aad83b2b2f108e5/src/documents/classifier.py#L40-L45

Thus it throws an error: https://github.com/paperless-ngx/paperless-ngx/blob/2b006907d536ce6e79f4c0c5ff0a9cd9e32fab66/src/documents/views.py#L1623-L1625

If you can wait a few minutes, Paperless should generate the model and the ERROR will be gone.

But I do agree that this is a bad experience. Probably someone could help with a fix: Stop checking System Status in the first few minutes, or, have a special condition saying the classifier is not ready and asks users to come back later.

<img width="1140" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/10862845/d7853524-b683-4541-b4ec-8a526f068a11">

**Comment by shamoon** [comment]
The status page is trying to load the classifier and failing, which would indicate an actual problem with it. Thats the purpose of this feature.

Im not sure I agree this is a bug, the classifier hasn't been generated yet, which means its not there.

To me, the question is whether users who are seeing this actually have a working classifier (or some other issue that makes showing an error status inaccurate).

**Comment by jxtxzzw** [comment]
I see your point: Status page loads the classifier, and it fails, so it reports an error. This is intended. This is not a bug because status match. Only when the actual classifier status doesn't match the status page, it is a bug.

Probably we can say this an enhancement, rather than a bug fix.

My point here is, since people (e.g., Flol0, tom666-debug) having concerns/confusions here, it indicates a bad thing and should be improved: From a engineer's perspective, I understand what is happening, but from a user's perspective, I would assume something is wrong as long as I see a red cross mark on my screen. I won't understand the classifier hasn't been generated, and the error will be gone once the model is trained. Thus, users will report it as a bug, just because they updated Paperless and see a red cross mark - That's so intuitive.

In my humble opinion, if "a classifier is not there" is a part of a correct workflow (which I assume is, especially when Paperless is just restarted), then we shouldn't take it as an error. An error means "a classifier should be there but it's not". Here, the thing is "a classifier is being generated -> so we can't load it + because we can't load it, it indicates an error" ==> "a classifier is being generated, so this indicates an error".

What about taking logger.exception as a failure in System Status Page, and ignoring logger.info and logger.debug? Or maybe we can re-write the error message as "Classifier not loaded. Probably it hasn't been generated. Please check again later." and use another icon for this status (not a green check mark or a red cross mark - maybe a ).

**Comment by shamoon** [comment]
Obviously I see your point, my fear with the status page was that it would cause noise like this.

I'm going to re-open this just so we dont get a bunch of duplicate reports.

**Comment by do4bmw** [comment]
same for me , and after this error , the importer doesnt import any documents
if i restart the container , import is running trough , and then this error pops up and the system dont want to import.
so i have to reboot again

![image](https://github.com/paperless-ngx/paperless-ngx/assets/76187206/31090af0-2702-4006-917c-e87225ad15b1)

**Comment by shamoon** [comment]
@do4bmw that sounds unrelated. You should search and read the documentation for issues with the consumer (assuming thats what you mean by 'import')

**Comment by shamoon** [comment]
Please read the thread. 2.6.1 will be out shortly and changes this to hopefully be clearer. Any other issues users can start a discussion thread
