### ISSUE TITLE
[BUG] Ctrl+arrows in text boxes should move the cursor, and not change documents (regression)

### ISSUE THREAD

**Issue by denilsonsa** [paperless-ngx/paperless-ngx#6642]
### Description

#6449 introduced several hotkeys, including `Ctrl + →` and `Ctrl + ←` to navigate to the next/previous document. Unfortunately, these keyboard shortcuts clash with native keys to move the cursor around.

### Steps to reproduce

1. Search for documents, or open a view.
2. Edit one.
3. Focus on one of the many text fields.
4. Use `Ctrl + →` and `Ctrl + ←` to quickly move the cursor between words.
    * This shortcut exists on both Linux and Windows for decades. I've never used a Mac, so I'm not sure if it applies to that system.

What happens: The cursor doesn't move. Instead, another document is opened.

## Why it matters

* Native key bindings should be respected and not overridden. (Unless in very exceptional cases.)
* I'm often moving the cursor around to select parts of the text so I can edit the document title.
    * Maybe I want to quickly capitalize the first letter of each word, and thus `Ctrl + arrow` followed by `Delete` and the new letter is the quickest way.
    * Maybe I want to quickly delete some words, so `Ctrl + arrow` to move the cursor to a word boundary, followed by `Ctrl + Shift + arrow` to select one or more words.

## Source-code

`hot-key.service.ts` already ignores custom shortcuts if the focus is on an Input or TextArea element, but only if those shortcuts don't have any modifiers:

https://github.com/paperless-ngx/paperless-ngx/blob/v2.8.2/src-ui/src/app/services/hot-key.service.ts#L47-L56

Oddly, `HTMLSelectElement` isn't included, which may be an oversight that will cause trouble some time in the future.

`document-detail.component.ts` now has a few shortcuts:

https://github.com/paperless-ngx/paperless-ngx/blob/v2.8.2/src-ui/src/app/components/document-detail/document-detail.component.ts#L461-L493

* `Escape`, which works as expected, I think.
* `Ctrl + →` and `Ctrl + ←`, which clashes with the native shortcuts.
* `Ctrl + S`, which probably works but I haven't tested.

## Suggestions

I believe `Ctrl + S` should work even when a text element is focused, as it doesn't clash with any shortcut and it makes sense to have it always enabled.

However, `Ctrl + Arrows` do clash with native shortcuts. Either they should only be handled when no text field is focused, or a new pair of hotkeys should be chosen.

I'd avoid "modifiers + arrows", as those are over-used and likely to clash:

| Shift | Ctrl | Alt | Keys | Native behavior |
| ----- | ---- | --- | ---- | - |
|       |      |     |Arrows| Move the cursor or scroll the page/element. |
|       | Ctrl |     | ← / →| Move the cursor over words. |
|       | Ctrl |     | ↑ / ↓| Unused? |
| Shift |      |     |Arrows| Start/extend text selection. |
| Shift | Ctrl |     |Arrows| Move the cursor while extending selection. |
| Shift | Ctrl |     | ↑ / ↓| Unused? Behaves just like Shift+Arrows. |
|       |      | Alt | ← / →| Navigate browser history (Back/Forward). |
|       |      | Alt | ↑ / ↓| Unused? |
|       | Ctrl | Alt |Arrows| Changes the virtual desktop in some desktop environments. |
| Shift |      | Alt |Arrows| Unused? ([Maybe relevant on Windows](https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec).) |
| Shift | Ctrl | Alt |Arrows| Unused? But also difficult to execute. |
|       | Fn / Cmd |     |Arrows| Emulates Home/End/PageUp/PageDown on some systems. |

I would suggest using `j`/`k` as the shortcuts, as these are used in many other places (e.g. Gmail). If we are going to stick to the arrows, I'd suggest `Alt + Up/Down`.

## Footnotes

I was unsure if I should open this as a bug or as a discussion. Since this is a regression, and it affects many people, and it is something that should behave a certain way but now it doesn't anymore… I think it qualifies as a bug.

### Webserver logs

```bash
Not relevant.
```

### Paperless-ngx version

2.8.1

### Host OS

Not relevant

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Thanks for taking the time to write this up, and for your participation here in general. Im closing it because:

1. Most importantly, this was changed in 2.8.2. Your report is from 2.8.1 but the source code you linked to does just this, i.e. when an arrow is pressed (with or without modifier keys) its ignored by the hotkey service.
2. In general, Im happy to discuss changes like this in discussions, but I dont see it as a bug either way. Before implementing the hotkeys I did a bunch of research and there really is no consensus about how web apps handle shortcut keys, some do override system things, others dont. I did my best to think carefully about which to choose and where, but I realize not everyone will be happy with all the choices I made, and unfortunately we dont have a bank of QA testers or a UX team, etc. etc.

Thanks again for your input (hey, thats a pun).

**Comment by denilsonsa** [comment]
Thanks! The 2.8.2 version was released so quickly! (And that's not a complaint.) I did look into the changelog, and I did check any recent issue, PR, or discussion, but I couldn't find any mention to hotkeys or shortcuts. I wrongly assumed this wasn't fixed in 2.8.2. I should have followed the best practices of always testing the latest version.

Thanks for the incredible amount of work you've been doing, and sorry for the noise.

**Comment by shamoon** [comment]
No worries. Yesterday was a bit of a mad dash and (not the first time I’ve done this) I accidentally committed the change directly into the branch so there’s no PR etc.

also just wanted to add a little context to the above that I forgot to add earlier, which is part of the reason we prefer to talk about changes in discussion format as opposed to “bug reports“ is so that we can try to solicit more opinions ie to avoid being overly-reactive to a single opinion. I long ago accepted that you simply cannot please all the people all the time, so whenever possible I prefer to make changes with at least some sense of how much sentiment varies. Believe me, I wish I had better ways to avoid working in a vacuum but with our small team and the reality of FOSS work, this is sorta what we got. I’m always open to discuss other ideas on how things should work, and I do try to use discussions as at least jumping off points (or more) for new features.

Anyway, thanks again for your interest in the project
