### ISSUE TITLE
[BUG] Only super admins can log in after upgrade from 2.9.0 to 2.10.1

### ISSUE THREAD

**Issue by leimer** [paperless-ngx/paperless-ngx#7036]
### Description

When logging in as normal user, ui_settings endpoint returns 403 Forbidden
```
{"detail":"Sie sind nicht berechtigt diese Aktion durchzuführen."}
```

Promoting the normal user as super admin enables the login again.

Looking at the diff of https://github.com/paperless-ngx/paperless-ngx/compare/v2.9.0...v2.10.1
Those two commits might be involved here.
6d2ae3d
b6f6d52

### Steps to reproduce

1. Create a normal user on version 2.9.0
2. Upgrade to 2.10.1
3. try to log in as the user above
![image](https://github.com/paperless-ngx/paperless-ngx/assets/1557648/83e6d4e4-3aa7-42ad-bbc8-fdd951ed3399)

Login as super user is fully functional.

### Webserver logs

```bash
[2024-06-19 16:45:32,333] [WARNING] [django.request] Forbidden: /api/ui_settings/
```

### Paperless-ngx version

2.10.1

### Host OS

Synology DSM 7.2.1-69057 Update 5

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.10.1",
    "server_os": "Linux-4.4.302+-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 32610140491776,
        "available": 18299767070720
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-06-19T14:25:15.617963+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-06-19T14:05:05.141857Z",
        "classifier_error": null
    }
}
```

### Browser

Safari, Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
users will need ui_settings to login, that technically should always have been the case

**Comment by leimer** [comment]
Thanks for the very quick reply. Indeed, my user didn't have the ui_settings permission.
I can assure you, that my login worked in the past.
Could it be that the permission assertion was not working as expected in the past?

My configuration issue is solved. Thank you :-)

**Comment by lennon101** [comment]
yeah this just caught me out as well. I didn't have that `ui_settings` permissions enabled while on v2.9 and users who weren't super/admin could still access the UI. Then I upgraded to 2.11 and oops! Took me a while to figure out what was going wrong. Glad I found this issue 😂

**Comment by JoergPalmer** [comment]
> yeah this just caught me out as well. I didn't have that `ui_settings` permissions enabled while on v2.9 and users who weren't super/admin could still access the UI. Then I upgraded to 2.11 and oops! Took me a while to figure out what was going wrong. Glad I found this issue 😂

I'm facing the same problem after updating to v2.11.
Could someone let me know how I could check/change the permissions when I'm not able to logon? Can this be done on database level?

**Comment by lennon101** [comment]
@JoergPalmer I'm going to go out on a limb here and guess that the reason why you can't login is because you've tried to login with an account that doesn't have those permissions and you're stuck at that waiting screen? I found this issue as well and felt I was completely locked out but then I realised that if you go to a different browser on the same machine (e.g. if you were using chrome switch to Firefox or something) or even just try on a different computer, and login with a different account that has admin privileges. Obviously don't use the same account to login that you've been locked out of. Does that make sense?

Either way, you're going to need to login using another account that DOES have admin/super user privilages.

**Comment by JoergPalmer** [comment]
> @JoergPalmer I'm going to go out on a limb here and guess that the reason why you can't login is because you've tried to login with an account that doesn't have those permissions and you're stuck at that waiting screen? I found this issue as well and felt I was completely locked out but then I realised that if you go to a different browser on the same machine (e.g. if you were using chrome switch to Firefox or something) or even just try on a different computer, and login with a different account that has admin privileges. Obviously don't use the same account to login that you've been locked out of. Does that make sense?
> 
> Either way, you're going to need to login using another account that DOES have admin/super user privilages.

Well, honestly I'm not sure whether my account has that permission or not. When trying to logon, the system tells me the username or password is wrong. Needless to say, it is the very same account that worked for years. This problem came to the surface only after the update to v2.11. 

The account has admin privileges. My system holds 4 accounts, and that is the only one with admin rights. If logging on is a must to fix the problem, I'm at a loss.

I thought about setting a new superuser with the help of the manage.py tool. But then the question is, does this wipe all my content? I could live with re-building all the users, but I would regret loosing my documents and their meta-data.

**Comment by lennon101** [comment]
Yeah, no worries at all. It doesn't sound like the same problem. And it also doesn't sound like an issue so I wouldn't be opening an issue, instead open a discussion and ask for help there. Hope that makes sense and good luck. I'll jump over into that discussion once you post and see if I can help.

**Comment by Benny-Git** [comment]
> Yes I think it was not working correctly and now is, so things were sort of unintentionally working for some users before. I will add a heads up to the release notes, thanks

@shamoon I just ran into the same issue and did not see anything in the [changelog](https://docs.paperless-ngx.com/changelog/) regarding this. I would have expected this listed as "Breaking Changes"?
