### ISSUE TITLE
[BUG] after Upgrade to NGX, save buttons don't work

### ISSUE THREAD

**Issue by qcasey** [paperless-ngx/paperless-ngx#716]
### Discussed in https://github.com/paperless-ngx/paperless-ngx/discussions/714

<div type='discussions-op-text'>

<sup>Originally posted by **as0bit** April 12, 2022</sup>
Hello,
I am working with Paperless-NG in Docker. After the upgrade to V1.6.0, the save buttons are there when editing the document but cannot be clicked. There is also no color change with the mouse (hover).

I've also tried Firefox and Edge.
Does somebody has any idea?

THX as0bit</div>

**Comment by shamoon** [comment]
He's reporting that in 1.6.0 and I cant confirm it in either, can you?

**Comment by qcasey** [comment]
Ah, I missed that. No I can't reproduce either.

**Comment by Profex** [comment]
I faced similar while I was on 1.7.0-rc1, but did not report it that time. So I assume it's actually connected to the 1.7.0-rc1 release, despite 1.6.0 is mentioned. For 1.6.0 I cannot reproduce either.

Since watchtower downgraded me to 1.6.0 again can't check on this again right now, but I am planning to manually upgrade to 1.7.0-rc1 again soon, and then can check again on this

**Comment by shamoon** [comment]
Can be re-opened if reproducible.

**Comment by vsspace** [comment]
I can reproduce this problem on my system in 1.6.0 as well.
If you change the name afterwards without leaving the focus of the field, the save button needs about 1-2 seconds until it becomes active. Of course, this may be due to the performance of the system, but I did not have this problem before.
But if I change the date field afterwards, the save button remains inactive the whole time. I must then first click on another field so that the save button becomes active.
Is of course quite annoying if you quickly change the date and simply want to save, but must first click somewhere else.

**Comment by shamoon** [comment]
Not really a “bug”. Please see https://github.com/paperless-ngx/paperless-ngx/issues/569
